CREATE TABLE gm_registros(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Perfil INT NOT NULL
);

CREATE TABLE gm_users(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    User VARCHAR(255) NOT NULL,
    Senha VARCHAR(255) NOT NULL
);
